// AUTO-GENERATED by scripts/refresh-metadata.ts. Edit the script, not this file.

export interface FeedEntry {
  index: number;
  version: string;
  ref: string;
  publishedAt: number;
}

export const feedEntries: FeedEntry[] = [

];
