// AUTO-GENERATED by scripts/refresh-metadata.ts. Edit the script, not this file.

export interface DemoMetadata {
  ref: string | null;
  index: number | null;
  owner: string | null;
  version: string | null;
  publishedAt: number | null;
  packageName: string;
  gateway: string;
}

export const metadata: DemoMetadata = {
  ref: null,
  index: null,
  owner: null,
  version: null,
  publishedAt: null,
  packageName: "dappswarm-demo",
  gateway: "https://api.gateway.ethswarm.org",
};
